## <mark>**Pandas**<maark/>:

```
Pandas is an open-source Python library used for data manipulation and data analysis, especially with structured data in the form of tables (rows and columns).
PANDAS = Panel Data Analysis.
“Panel Data” refers to data that has multiple dimensions (like time, rows, columns).
Pandas was designed to handle this type of structured data efficiently.

Pandas is a library used to:

- Load data
- Clean data
- Analyze data
- Manipulate data

It works especially well with tables (like Excel sheets or CSV files).

### <mark>**Series : A series is a one dimensional labelled vertical array**<mark/>

Series is a single column of data with label(index)

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [3]:
s1 = pd.Series(my_list)
s1

0    10
1    20
2    30
dtype: int64

In [6]:
s2 = pd.Series(my_list,index=labels)
s2

a    10
b    20
c    30
dtype: int64

In [7]:
s3 = pd.Series(arr)
s3

0    10
1    20
2    30
dtype: int64

In [9]:
s4 = pd.Series(d)
s4

1    10
2    20
3    30
dtype: int64

#### <mark>**DataFrame : A DataFrame is a two-dimensional (2D) data structure in Pandas that stores data in rows and columns (like a table).**<mark/>

DataFrame is collection of multiple series(column) forming a table.

In [10]:
data = {
    "Name": ["Rohan", "Amit", "Neha"],
    "Age": [21, 22, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(data)
print(df)

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [11]:
data = [
    ["Rohan", 21, "Delhi"],
    ["Amit", 22, "Mumbai"],
    ["Neha", 20, "Pune"]
]
columns_name = ["Name","Age","city"]
df2 = pd.DataFrame(data,columns=columns_name)
df2

    Name  Age    city
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

### <mark>**Selection and indexing of Columns**<mark/>

In [13]:
data = {
    "Name": ["Rohan", "Amit", "Neha"],
    "Age": [21, 22, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df3 = pd.DataFrame(data)
df3

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [15]:
# select single ccolumns
df3["Name"]

0    Rohan
1     Amit
2     Neha
Name: Name, dtype: object

In [16]:
# selecting multiple ccolumns_name
df3[["Name","Age"]]

    Name  Age
0  Rohan   21
1   Amit   22
2   Neha   20

#### <mark>**Selecting column using dot**<mark/>

In [17]:
df3.Name

0    Rohan
1     Amit
2     Neha
Name: Name, dtype: object

In [20]:
df3.City

0     Delhi
1    Mumbai
2      Pune
Name: City, dtype: object

**<mark>Note: Works only if column name has no space<mark/>**

### **<mark>Adding a new column<mark/>**

In [21]:
df3

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [22]:
df3["Designation"] = ["data scientist","software engineer","ML engineer"]
df3

    Name  Age    City        Designation
0  Rohan   21   Delhi     data scientist
1   Amit   22  Mumbai  software engineer
2   Neha   20    Pune        ML engineer

In [23]:
df3["Experience"] = ["Fresher","1yr","3yrs"]
df3

    Name  Age    City        Designation Experience
0  Rohan   21   Delhi     data scientist    Fresher
1   Amit   22  Mumbai  software engineer        1yr
2   Neha   20    Pune        ML engineer       3yrs

### <mark>**Removing a column**<mark/>

In [24]:
df3.drop("Designation",axis=1) # you have to give axis=1 to remove column because defaut value of axis is 0 it will try to remove row name with designation

    Name  Age    City Experience
0  Rohan   21   Delhi    Fresher
1   Amit   22  Mumbai        1yr
2   Neha   20    Pune       3yrs

In [25]:
df3 # you can see it does not affect the original dataframe it to delete the column for original dataframe we have to use inplace attribute

    Name  Age    City        Designation Experience
0  Rohan   21   Delhi     data scientist    Fresher
1   Amit   22  Mumbai  software engineer        1yr
2   Neha   20    Pune        ML engineer       3yrs

In [26]:
df3.drop("Designation",axis=1,inplace=True)

In [27]:
df3 # now you can see Designation is removed permanently from dataframe

    Name  Age    City Experience
0  Rohan   21   Delhi    Fresher
1   Amit   22  Mumbai        1yr
2   Neha   20    Pune       3yrs

### **Removing multiple columns**

In [29]:
df3.drop(["Name","Age"],axis=1)

     City Experience
0   Delhi    Fresher
1  Mumbai        1yr
2    Pune       3yrs