## <mark>**Pandas**<maark/>:

```
Pandas is an open-source Python library used for data manipulation and data analysis, especially with structured data in the form of tables (rows and columns).
PANDAS = Panel Data Analysis.
“Panel Data” refers to data that has multiple dimensions (like time, rows, columns).
Pandas was designed to handle this type of structured data efficiently.

Pandas is a library used to:

- Load data
- Clean data
- Analyze data
- Manipulate data

It works especially well with tables (like Excel sheets or CSV files).

### <mark>**Series : A series is a one dimensional labelled vertical array**<mark/>

Series is a single column of data with label(index)

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [3]:
s1 = pd.Series(my_list)
s1

0    10
1    20
2    30
dtype: int64

In [6]:
s2 = pd.Series(my_list,index=labels)
s2

a    10
b    20
c    30
dtype: int64

In [7]:
s3 = pd.Series(arr)
s3

0    10
1    20
2    30
dtype: int64

In [9]:
s4 = pd.Series(d)
s4

1    10
2    20
3    30
dtype: int64

#### <mark>**DataFrame : A DataFrame is a two-dimensional (2D) data structure in Pandas that stores data in rows and columns (like a table).**<mark/>

DataFrame is collection of multiple series(column) forming a table.

In [10]:
data = {
    "Name": ["Rohan", "Amit", "Neha"],
    "Age": [21, 22, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(data)
print(df)

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [11]:
data = [
    ["Rohan", 21, "Delhi"],
    ["Amit", 22, "Mumbai"],
    ["Neha", 20, "Pune"]
]
columns_name = ["Name","Age","city"]
df2 = pd.DataFrame(data,columns=columns_name)
df2

    Name  Age    city
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

### <mark>**Selection and indexing of Columns**<mark/>

In [13]:
data = {
    "Name": ["Rohan", "Amit", "Neha"],
    "Age": [21, 22, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df3 = pd.DataFrame(data)
df3

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [15]:
# select single ccolumns
df3["Name"]

0    Rohan
1     Amit
2     Neha
Name: Name, dtype: object

In [16]:
# selecting multiple ccolumns_name
df3[["Name","Age"]]

    Name  Age
0  Rohan   21
1   Amit   22
2   Neha   20

#### <mark>**Selecting column using dot**<mark/>

In [17]:
df3.Name

0    Rohan
1     Amit
2     Neha
Name: Name, dtype: object

In [20]:
df3.City

0     Delhi
1    Mumbai
2      Pune
Name: City, dtype: object

**<mark>Note: Works only if column name has no space<mark/>**

### **<mark>Adding a new column<mark/>**

In [21]:
df3

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [22]:
df3["Designation"] = ["data scientist","software engineer","ML engineer"]
df3

    Name  Age    City        Designation
0  Rohan   21   Delhi     data scientist
1   Amit   22  Mumbai  software engineer
2   Neha   20    Pune        ML engineer

In [23]:
df3["Experience"] = ["Fresher","1yr","3yrs"]
df3

    Name  Age    City        Designation Experience
0  Rohan   21   Delhi     data scientist    Fresher
1   Amit   22  Mumbai  software engineer        1yr
2   Neha   20    Pune        ML engineer       3yrs

### <mark>**Removing a column**<mark/>

In [24]:
df3.drop("Designation",axis=1) # you have to give axis=1 to remove column because defaut value of axis is 0 it will try to remove row name with designation

    Name  Age    City Experience
0  Rohan   21   Delhi    Fresher
1   Amit   22  Mumbai        1yr
2   Neha   20    Pune       3yrs

In [25]:
df3 # you can see it does not affect the original dataframe it to delete the column for original dataframe we have to use inplace attribute

    Name  Age    City        Designation Experience
0  Rohan   21   Delhi     data scientist    Fresher
1   Amit   22  Mumbai  software engineer        1yr
2   Neha   20    Pune        ML engineer       3yrs

In [26]:
df3.drop("Designation",axis=1,inplace=True)

In [27]:
df3 # now you can see Designation is removed permanently from dataframe

    Name  Age    City Experience
0  Rohan   21   Delhi    Fresher
1   Amit   22  Mumbai        1yr
2   Neha   20    Pune       3yrs

### **Removing multiple columns**

In [29]:
df3.drop(["Name","Age"],axis=1)

     City Experience
0   Delhi    Fresher
1  Mumbai        1yr
2    Pune       3yrs

#### <mark>**Selecting Rows**<mark/>

<mark>**loc : loc is a label-based indexing method in Pandas used to select rows and columns using their names (labels).**<mark/>

**loc[row, column]**

In [6]:
import numpy as np
import pandas as pd
data = {
    "Name": ["Rohan", "Amit", "Neha"],
    "Age": [21, 22, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df4 = pd.DataFrame(data)
df4

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [10]:
df4.loc[0]

Name    Rohan
Age        21
City    Delhi
Name: 0, dtype: object

In [11]:
df4.loc[0,"Name"]

'Rohan'

In [13]:
df4.loc[: ,"Name"] # it selects all rows(:)

0    Rohan
1     Amit
2     Neha
Name: Name, dtype: object

In [15]:
df4.loc[[0,1]] # selecting multiple rows

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai

<mark>**iloc : iloc is a position-based indexing method in Pandas used to select rows and columns using their integer index positions.**<mark/>

#### <mark>**Selecting subsets of row and column**<mark/>

In [16]:
df4

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [20]:
df4.loc[[0,1]][["Name","Age"]]

    Name  Age
0  Rohan   21
1   Amit   22

<mark>**Conditional Selection**<mark/>

In [21]:
df4

    Name  Age    City
0  Rohan   21   Delhi
1   Amit   22  Mumbai
2   Neha   20    Pune

In [22]:
df4[df4["Age"]>21]

   Name  Age    City
1  Amit   22  Mumbai

In [23]:
df4[(df4["Age"]>20)&(df4["City"]=="Delhi")]

    Name  Age   City
0  Rohan   21  Delhi

In [24]:
Data = {
    "name" : ["rohan","golu","amar","kishan"],
    "age" : [20,12,24,21],
    "salary" : [10000,12000,13000,11000],
    "designation" : ["data scientist","software engineer","fashion designer","analyst"]
}
df5 = pd.DataFrame(Data)
df5

     name  age  salary        designation
0   rohan   20   10000     data scientist
1    golu   12   12000  software engineer
2    amar   24   13000   fashion designer
3  kishan   21   11000            analyst

In [28]:
df5.loc[[0,2]]

    name  age  salary       designation
0  rohan   20   10000    data scientist
2   amar   24   13000  fashion designer

In [29]:
df5.loc[0,"name"]

'rohan'

In [30]:
df5[(df5["age"]>18)&(df5["salary"]>11000)]

   name  age  salary       designation
2  amar   24   13000  fashion designer

#### <mark>**Missing Data**<mark/>

```
Missing data means some values are not present in the dataset.
In Pandas, missing values are shown as:
NaN (Not a Number).

In [5]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Rohan", "Amit", "Neha"],
    "Age": [21, np.nan, 20],
    "City": ["Delhi", "Mumbai", np.nan ]
}
df = pd.DataFrame(data)
df

    Name   Age    City
0  Rohan  21.0   Delhi
1   Amit   NaN  Mumbai
2   Neha  20.0     NaN

#### **<mark>Checking Missing Data**<mark/>

**<mark>df.isna()/df.isnull() : Returns a boolean DataFrame showing True for missing values (NaN) and False otherwise.<mark/>**

In [7]:
df.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True

In [8]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True

**<mark>isna().sum() : Counts total missing values in each column (or row if axis is changed)**<mark/>
```
Works on:
Columns (default)
Rows → axis=1

In [9]:
df.isna().sum()

Name    0
Age     1
City    1
dtype: int64

In [11]:
df.isna().sum(axis=1)

0    0
1    1
2    1
dtype: int64

<mark>**isna().any() :  checks if there is at least one missing value (NaN) .Returns True if any missing value is present, otherwise False.**<mark/>
```
Works on:
Columns (default)
Rows → axis=1

In [12]:
df.isna().any()

Name    False
Age      True
City     True
dtype: bool

In [13]:
df.isna().any(axis=1)

0    False
1     True
2     True
dtype: bool

**<mark>notna() / notnull() : Returns True for non-missing values and False for missing values.<mark/>**

In [14]:
df.notna()

   Name    Age   City
0  True   True   True
1  True  False   True
2  True   True  False

In [15]:
df

    Name   Age    City
0  Rohan  21.0   Delhi
1   Amit   NaN  Mumbai
2   Neha  20.0     NaN

#### **<mark>Removing Missing Data<mark/>**